<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageId>ASCOM.Alpaca.Templates</PackageId>
    <Title>ASCOM Alpaca .Net Template</Title>
    <Authors>Daniel Van Noord</Authors>
    <Description>Template to use when creating an ASCOM Alpaca C# Driver using Blazor, Razor and ASP.Net Core.</Description>
    <PackageTags>dotnet-new;templates;ASCOM;alpaca</PackageTags>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <EnableDefaultItems>false</EnableDefaultItems>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.5.0-alpha04</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="AlpacaDriverDemo\**"
          Exclude="AlpacaDriverDemo\bin\**;
                 AlpacaDriverDemo\obj\**"
          Pack="true"
          PackagePath="" />
    <None Update="AlpacaDriverDemo\CustomisationHelp\CSharpAlpacaTemplate.docx"
          Pack="false" />
  </ItemGroup>

</Project>